-- Module Tournées : sites desservis, tournées et arrêts (avec preuve de passage).

CREATE TABLE site (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES company(id),
    name VARCHAR(255) NOT NULL,
    kind VARCHAR(32) NOT NULL
        CHECK (kind IN ('DEPOT','CLIENT','PHARMACIE','LABORATOIRE','ETABLISSEMENT_SANTE','AUTRE')),
    reference VARCHAR(255),
    address VARCHAR(255),
    postal_code VARCHAR(255),
    city VARCHAR(255),
    latitude FLOAT(53),
    longitude FLOAT(53),
    contact_name VARCHAR(255),
    contact_phone VARCHAR(255),
    opening_from TIME(6),
    opening_to TIME(6),
    service_minutes INTEGER,
    notes VARCHAR(1000),
    active BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE INDEX idx_site_company ON site(company_id);

CREATE TABLE tour (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES company(id),
    name VARCHAR(255) NOT NULL,
    tour_date DATE NOT NULL,
    driver_id BIGINT REFERENCES driver(id),
    truck_id BIGINT REFERENCES truck(id),
    depot_id BIGINT REFERENCES site(id),
    planned_start TIME(6) NOT NULL,
    status VARCHAR(32) NOT NULL
        CHECK (status IN ('PLANIFIEE','EN_COURS','TERMINEE','ANNULEE')),
    planned_distance_km FLOAT(53),
    planned_duration_minutes INTEGER,
    optimized_at TIMESTAMP(6),
    started_at TIMESTAMP(6),
    completed_at TIMESTAMP(6),
    notes VARCHAR(1000)
);
CREATE INDEX idx_tour_company_date ON tour(company_id, tour_date);
CREATE INDEX idx_tour_driver_date ON tour(driver_id, tour_date);

CREATE TABLE tour_stop (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES company(id),
    tour_id BIGINT NOT NULL REFERENCES tour(id),
    site_id BIGINT NOT NULL REFERENCES site(id),
    stop_sequence INTEGER NOT NULL,
    stop_type VARCHAR(32) NOT NULL CHECK (stop_type IN ('LIVRAISON','ENLEVEMENT','COLLECTE')),
    window_start TIME(6),
    window_end TIME(6),
    service_minutes INTEGER NOT NULL,
    planned_arrival TIME(6),
    planned_lateness_minutes INTEGER,
    status VARCHAR(32) NOT NULL CHECK (status IN ('A_FAIRE','FAIT','ECHEC')),
    arrived_at TIMESTAMP(6),
    completed_at TIMESTAMP(6),
    signed_by VARCHAR(255),
    parcel_count INTEGER,
    sample_count INTEGER,
    temperature_celsius FLOAT(53),
    temperature_min_celsius FLOAT(53),
    temperature_max_celsius FLOAT(53),
    scanned_codes VARCHAR(2000),
    failure_reason VARCHAR(255),
    notes VARCHAR(1000)
);
CREATE INDEX idx_tour_stop_tour ON tour_stop(tour_id, stop_sequence);
CREATE INDEX idx_tour_stop_site ON tour_stop(site_id);
CREATE INDEX idx_tour_stop_company ON tour_stop(company_id);
