-- Commandes à planifier (import CSV / saisie) avant répartition automatique en tournées.

CREATE TABLE delivery_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES company(id),
    order_date DATE NOT NULL,
    site_id BIGINT NOT NULL REFERENCES site(id),
    reference VARCHAR(255),
    stop_type VARCHAR(32) NOT NULL CHECK (stop_type IN ('LIVRAISON','ENLEVEMENT','COLLECTE')),
    window_start TIME(6),
    window_end TIME(6),
    service_minutes INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    temperature_min_celsius FLOAT(53),
    temperature_max_celsius FLOAT(53),
    notes VARCHAR(1000),
    status VARCHAR(32) NOT NULL CHECK (status IN ('A_PLANIFIER','PLANIFIEE')),
    tour_stop_id BIGINT UNIQUE REFERENCES tour_stop(id),
    created_at TIMESTAMP(6) NOT NULL
);
CREATE INDEX idx_delivery_order_company_date ON delivery_order(company_id, order_date, status);
