-- Schéma de référence PostgreSQL, généré depuis les entités JPA (Hibernate schema
-- export, dialecte PostgreSQL) au moment de l'introduction de Flyway.
--
-- Aucune donnée de production ne dépend encore de ce schéma : c'est la baseline V1
-- à partir de laquelle toute évolution future du modèle doit passer par une nouvelle
-- migration versionnée (V2__..., V3__...), plus jamais par `ddl-auto: update`.
--
-- Généré via H2 en mode compatibilité PostgreSQL (pas de serveur Postgres disponible
-- au moment de la génération) : à valider par un `flyway migrate` sur un vrai
-- PostgreSQL 16 avant le tout premier déploiement en production.

create table app_user (enabled boolean not null, company_id bigint, created_at timestamp(6), id bigint generated by default as identity, invite_token_expires_at timestamp(6), reset_token_expires_at timestamp(6), display_name varchar(255) not null, email varchar(255), invite_token varchar(255), password varchar(255) not null, reset_token varchar(255), role varchar(255) not null, username varchar(255) not null unique, primary key (id));
create table assignment (active boolean not null, end_date date, start_date date not null, company_id bigint not null, driver_id bigint not null, id bigint generated by default as identity, truck_id bigint not null, primary key (id));
create table audit_log (company_id bigint, created_at timestamp(6) not null, id bigint generated by default as identity, user_id bigint, detail varchar(2000), action varchar(255) not null, ip_address varchar(255), username varchar(255), primary key (id));
create table company (created_at timestamp(6), id bigint generated by default as identity, last_trial_reminder_at timestamp(6), trial_ends_at timestamp(6), address varchar(255), billing_customer_id varchar(255), city varchar(255), contact_email varchar(255), contact_phone varchar(255), country varchar(255), legal_name varchar(255), name varchar(255) not null, plan varchar(255) not null check (plan in ('TRIAL','STARTER','PRO','ENTERPRISE')), postal_code varchar(255), siret varchar(255), status varchar(255) not null check (status in ('TRIAL','ACTIVE','SUSPENDED','CANCELLED')), subscription_id varchar(255), subscription_provider varchar(255), vat_number varchar(255), primary key (id));
create table cost_record (amount float(53) not null, company_id bigint not null, driver_id bigint not null, id bigint generated by default as identity, truck_id bigint not null, billing_month varchar(255) not null, category varchar(255) not null check (category in ('SALAIRE','CARBURANT','MAINTENANCE','ASSURANCE','AMORTISSEMENT','PEAGES','AUTRE')), primary key (id));
create table driver (active boolean not null, hire_date date, company_id bigint not null, id bigint generated by default as identity, email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, license_number varchar(255) not null, phone varchar(255) not null, primary key (id));
create table driving_event (duration_sec float(53), latitude float(53), longitude float(53), severity integer not null, speed_kph float(53), company_id bigint not null, driver_id bigint not null, id bigint generated by default as identity, timestamp timestamp(6) not null, truck_id bigint not null, type varchar(255) not null check (type in ('FREINAGE_BRUSQUE','ACCELERATION_FORTE','EXCES_VITESSE','RALENTI')), primary key (id));
create table fuel_record (amount float(53) not null, date date not null, liters float(53) not null, odometer_km float(53) not null, company_id bigint not null, id bigint generated by default as identity, truck_id bigint not null, primary key (id));
create table integration_config (enabled boolean not null, last_test_ok boolean, company_id bigint not null, created_at timestamp(6) not null, id bigint generated by default as identity, last_test_at timestamp(6), updated_at timestamp(6) not null, provider varchar(40) not null check (provider in ('GPS_WEBFLEET','GPS_WIALON','GPS_GEOTAB','GPS_TRACKER','TACHO_TACHOGRAM','TACHO_AS24','TACHO_TACHOSHARE','DHL','FUEL_AS24')), webhook_key varchar(64), api_key varchar(500), base_url varchar(500), last_test_message varchar(500), settings varchar(2000), primary key (id));
create table maintenance_record (cost float(53), done_date date, done_on_time boolean not null, planned boolean not null, scheduled_date date not null, company_id bigint not null, id bigint generated by default as identity, truck_id bigint not null, status varchar(255) not null check (status in ('PLANIFIE','REALISE','RETARDE')), type varchar(255) not null check (type in ('VIDANGE','FREINS','PNEUS','REVISION','CONTROLE_TECHNIQUE','REPARATION')), primary key (id));
create table notification (is_read boolean not null, company_id bigint not null, created_at timestamp(6) not null, entity_id bigint, id bigint generated by default as identity, user_id bigint, message varchar(2000), entity_type varchar(255), title varchar(255) not null, type varchar(255) not null check (type in ('MAINTENANCE_ECHEANCE','TACHYGRAPHIE_NON_CONFORME','TEMPS_CONDUITE','USAGE_ANORMAL','PAIEMENT')), primary key (id));
create table notification_rule (enabled boolean not null, threshold float(53), company_id bigint not null, id bigint generated by default as identity, type varchar(255) not null check (type in ('MAINTENANCE_ECHEANCE','TACHYGRAPHIE_NON_CONFORME','TEMPS_CONDUITE','USAGE_ANORMAL','PAIEMENT')), primary key (id));
create table tachograph_day (compliant boolean not null, date date not null, driving_hours float(53) not null, rest_minutes float(53) not null, work_hours float(53) not null, company_id bigint not null, driver_id bigint not null, id bigint generated by default as identity, primary key (id));
create table trip (cargo_weight_tons float(53), distance_km float(53) not null, end_km float(53), loaded boolean not null, on_time boolean not null, start_km float(53), company_id bigint not null, driver_id bigint not null, end_time timestamp(6) not null, id bigint generated by default as identity, start_time timestamp(6) not null, truck_id bigint not null, status varchar(255) not null check (status in ('EN_COURS','TERMINE','ANNULE')), primary key (id));
create table truck (acquisition_date date, active boolean not null, capacity_tons float(53), current_latitude float(53), current_longitude float(53), current_speed_kph float(53), expected_consumptionl100km float(53), model_year integer, purchase_price float(53), company_id bigint not null, id bigint generated by default as identity, last_gps_update timestamp(6), brand varchar(255) not null, current_status varchar(255) check (current_status in ('ROULAGE','ARRET','REPOS','ALERTE','IMMOBILISE')), fuel_type varchar(255) not null check (fuel_type in ('DIESEL','ELECTRIC')), model varchar(255) not null, registration varchar(255) not null, truck_type varchar(255) not null check (truck_type in ('TRACTEUR','PORTEUR','FOURGON')), primary key (id));
create index idx_audit_company_time on audit_log (company_id, created_at);
create index idx_integ_company on integration_config (company_id);
create index idx_notif_company_read on notification (company_id, is_read);
alter table if exists app_user add constraint FKcibobnb8xgty1t1ithfv41vkp foreign key (company_id) references company;
alter table if exists assignment add constraint FK1fqdgoyhaqkn5ymvfummj0etu foreign key (company_id) references company;
alter table if exists assignment add constraint FKlxyhk53rm4gb54bfipxr2i8p8 foreign key (driver_id) references driver;
alter table if exists assignment add constraint FKtfjdelm9r8cp8yrfokikobcdn foreign key (truck_id) references truck;
alter table if exists audit_log add constraint FKip9bmcrfidlgwf6pc2umkmjq8 foreign key (company_id) references company;
alter table if exists cost_record add constraint FK5u13q1njeaai2y81f2yyykw8r foreign key (company_id) references company;
alter table if exists cost_record add constraint FKro0cenb3jbsx4a48lvv40aw33 foreign key (driver_id) references driver;
alter table if exists cost_record add constraint FKpo8ot2u4fsfwg4ibjji88cfb6 foreign key (truck_id) references truck;
alter table if exists driver add constraint FKila7badj0hsdx1m0x5p6dj9hj foreign key (company_id) references company;
alter table if exists driving_event add constraint FKsh655lhetm6ttgf6mkbrdu39c foreign key (company_id) references company;
alter table if exists driving_event add constraint FK96q8xlx20b2bl97f9jbbrh0in foreign key (driver_id) references driver;
alter table if exists driving_event add constraint FKmw5jd9oe3xb18f6t29l0ahuac foreign key (truck_id) references truck;
alter table if exists fuel_record add constraint FKsstvavqa7xf3mppthd3rmk2l7 foreign key (company_id) references company;
alter table if exists fuel_record add constraint FKago5auwj1bv95ggq9poyvsfl5 foreign key (truck_id) references truck;
alter table if exists integration_config add constraint FKpx8n63h9hveql3yw2lnjvpxtw foreign key (company_id) references company;
alter table if exists maintenance_record add constraint FKfud6t1utj4caqoa1u4vigpkmh foreign key (company_id) references company;
alter table if exists maintenance_record add constraint FK8trjat0dn7g6j94aaw8fu9tfx foreign key (truck_id) references truck;
alter table if exists notification add constraint FKrk03rdyysb227p415gdpjmpqt foreign key (company_id) references company;
alter table if exists notification_rule add constraint FK1coc2iwyelwas7iwqn7mrodcv foreign key (company_id) references company;
alter table if exists tachograph_day add constraint FKk8vwnhna05fkbuondgvs2ekdt foreign key (company_id) references company;
alter table if exists tachograph_day add constraint FK73dxl4o0ibvlhg7fhlclc2u45 foreign key (driver_id) references driver;
alter table if exists trip add constraint FKd8xxxfscmdntnmtoqu3kuqbm3 foreign key (company_id) references company;
alter table if exists trip add constraint FKpuhkx68hnwy4by2b0onybv5x1 foreign key (driver_id) references driver;
alter table if exists trip add constraint FKbc3h4qiloke36aobtj4jub3os foreign key (truck_id) references truck;
alter table if exists truck add constraint FKr7mna3mw8vnooqau93jj7fxcq foreign key (company_id) references company;
