-- Table de révocation des tokens JWT.
-- Permet de déconnecter un utilisateur avant l'expiration naturelle du token (24h).
-- La colonne expires_at permet le nettoyage automatique des entrées expirées.

CREATE TABLE revoked_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    token_id   VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP(6) NOT NULL,
    revoked_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
);

CREATE INDEX idx_revoked_token_expires ON revoked_token (expires_at);
