export interface Country {
  code: string;
  name: string;
}

export const ORIGIN_COUNTRIES: Country[] = [
  { code: 'CN', name: 'Chine' },
  { code: 'US', name: 'États-Unis' },
  { code: 'JP', name: 'Japon' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'IN', name: 'Inde' },
  { code: 'TR', name: 'Turquie' },
  { code: 'MA', name: 'Maroc' },
  { code: 'KR', name: 'Corée du Sud' },
  { code: 'TH', name: 'Thaïlande' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'ID', name: 'Indonésie' },
  { code: 'BR', name: 'Brésil' },
  { code: 'MX', name: 'Mexique' },
  { code: 'CA', name: 'Canada' },
  { code: 'CL', name: 'Chili' },
  { code: 'AU', name: 'Australie' },
  { code: 'AR', name: 'Argentine' },
  { code: 'GB', name: 'Royaume-Uni' },
  { code: 'CH', name: 'Suisse' },
  { code: 'NO', name: 'Norvège' },
  { code: 'SG', name: 'Singapour' },
  { code: 'TN', name: 'Tunisie' },
  { code: 'ZA', name: 'Afrique du Sud' },
  { code: 'DE', name: 'Allemagne' },
  { code: 'IT', name: 'Italie' },
  { code: 'ES', name: 'Espagne' },
  { code: 'NL', name: 'Pays-Bas' },
  { code: 'BE', name: 'Belgique' },
  { code: 'PL', name: 'Pologne' },
  { code: 'PT', name: 'Portugal' },
  { code: 'BG', name: 'Bulgarie' },
  { code: 'RO', name: 'Roumanie' },
];

export const DEST_COUNTRIES: Country[] = [
  { code: 'FR', name: 'France' },
  { code: 'DE', name: 'Allemagne' },
  { code: 'IT', name: 'Italie' },
  { code: 'ES', name: 'Espagne' },
  { code: 'NL', name: 'Pays-Bas' },
  { code: 'BE', name: 'Belgique' },
  { code: 'PT', name: 'Portugal' },
  { code: 'PL', name: 'Pologne' },
  { code: 'AT', name: 'Autriche' },
  { code: 'IE', name: 'Irlande' },
  { code: 'FI', name: 'Finlande' },
  { code: 'SE', name: 'Suède' },
  { code: 'DK', name: 'Danemark' },
  { code: 'GR', name: 'Grèce' },
  { code: 'CZ', name: 'Tchéquie' },
  { code: 'RO', name: 'Roumanie' },
  { code: 'HU', name: 'Hongrie' },
  { code: 'BG', name: 'Bulgarie' },
  { code: 'HR', name: 'Croatie' },
  { code: 'SI', name: 'Slovénie' },
  { code: 'EE', name: 'Estonie' },
  { code: 'LV', name: 'Lettonie' },
  { code: 'LT', name: 'Lituanie' },
  { code: 'CY', name: 'Chypre' },
  { code: 'MT', name: 'Malte' },
  { code: 'LU', name: 'Luxembourg' },
  { code: 'GB', name: 'Royaume-Uni' },
];
