package com.incokalk.controller.compliance;

import com.incokalk.model.Company;
import com.incokalk.model.CompanyRole;
import com.incokalk.security.RequiresPlan;
import com.incokalk.security.RolesAllowed;
import com.incokalk.tenant.TenantContext;
import com.incokalk.service.DebAutoGenerationService;
import com.incokalk.service.DebAutoGenerationService.ShipmentData;
import com.incokalk.service.DebAutoGenerationService.DebGenerationResult;
import com.incokalk.service.FrenchFiscalService;
import com.incokalk.service.FrenchFiscalService.FrenchDutyBreakdown;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import jakarta.validation.Valid;
import java.math.BigDecimal;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@RestController
@RequestMapping("/v1/french-fiscal")
@RequiredArgsConstructor
@RequiresPlan(Company.Plan.PRO)
public class FrenchFiscalController {

    private final FrenchFiscalService frenchFiscalService;
    private final DebAutoGenerationService debAutoGenService;

    @GetMapping("/tai-rates")
    @RolesAllowed({CompanyRole.Role.OWNER, CompanyRole.Role.ADMIN, CompanyRole.Role.MANAGER, CompanyRole.Role.USER})
    public ResponseEntity<Map<String, BigDecimal>> getTAIRates() {
        return ResponseEntity.ok(Map.of(
                "2203", new BigDecimal("31.76"),
                "2204", new BigDecimal("31.76"),
                "2205", new BigDecimal("31.76"),
                "2208", new BigDecimal("17.72"),
                "2402", new BigDecimal("97.20")
        ));
    }

    @GetMapping("/accises")
    @RolesAllowed({CompanyRole.Role.OWNER, CompanyRole.Role.ADMIN, CompanyRole.Role.MANAGER, CompanyRole.Role.USER})
    public ResponseEntity<Map<String, BigDecimal>> getAcciseRates() {
        return ResponseEntity.ok(Map.of(
                "2203", new BigDecimal("31.76"),
                "2204", new BigDecimal("16.30"),
                "2205", new BigDecimal("16.30"),
                "2208", new BigDecimal("23.57"),
                "2402", new BigDecimal("59.88")
        ));
    }

    @GetMapping("/safeguard-duties")
    @RolesAllowed({CompanyRole.Role.OWNER, CompanyRole.Role.ADMIN, CompanyRole.Role.MANAGER, CompanyRole.Role.USER})
    public ResponseEntity<Map<String, BigDecimal>> getSafeguardDuties() {
        return ResponseEntity.ok(Map.of(
                "7203-7229", new BigDecimal("25.0"),
                "7301-7326", new BigDecimal("15.0")
        ));
    }

    @GetMapping("/regimes")
    @RolesAllowed({CompanyRole.Role.OWNER, CompanyRole.Role.ADMIN, CompanyRole.Role.MANAGER, CompanyRole.Role.USER})
    public ResponseEntity<List<String>> getActiveRegimes() {
        return ResponseEntity.ok(frenchFiscalService.getActiveRegimes());
    }

    @PostMapping("/calculate")
    @RolesAllowed({CompanyRole.Role.OWNER, CompanyRole.Role.ADMIN, CompanyRole.Role.MANAGER, CompanyRole.Role.USER})
    public ResponseEntity<FrenchDutyBreakdown> calculateFrenchDuties(
            @RequestBody Map<String, Object> request) {
        String hsCode = (String) request.get("hsCode");
        BigDecimal cifValue = new BigDecimal(request.get("cifValue").toString());
        BigDecimal netWeight = request.get("netWeightKg") != null
                ? new BigDecimal(request.get("netWeightKg").toString()) : BigDecimal.ZERO;
        String originCountry = (String) request.get("originCountry");
        String destinationCountry = (String) request.getOrDefault("destinationCountry", "FR");
        BigDecimal mfnRate = request.get("mfnDutyRate") != null
                ? new BigDecimal(request.get("mfnDutyRate").toString()) : BigDecimal.ZERO;

        FrenchDutyBreakdown breakdown = frenchFiscalService.calculateFrenchDuties(
                hsCode, cifValue, netWeight, originCountry, destinationCountry, mfnRate);

        return ResponseEntity.ok(breakdown);
    }

    @PostMapping("/deb/auto-generate")
    @RolesAllowed({CompanyRole.Role.OWNER, CompanyRole.Role.ADMIN, CompanyRole.Role.MANAGER})
    public ResponseEntity<DebGenerationResult> autoGenerateDeb(
            @RequestBody ShipmentData shipment) {
        UUID companyId = TenantContext.get();
        DebGenerationResult result = debAutoGenService.generateDebFromShipment(shipment, companyId);
        return ResponseEntity.ok(result);
    }

    @PostMapping("/deb/bulk-generate")
    @RolesAllowed({CompanyRole.Role.OWNER, CompanyRole.Role.ADMIN, CompanyRole.Role.MANAGER})
    public ResponseEntity<DebGenerationResult> bulkGenerateDeb(
            @RequestBody Map<String, Object> request) {
        UUID companyId = TenantContext.get();
        List<ShipmentData> shipments = (List<ShipmentData>) request.get("shipments");
        int reportingPeriod = (int) request.get("reportingPeriod");
        DebGenerationResult result = debAutoGenService.generateBulkDeb(companyId, shipments, reportingPeriod);
        return ResponseEntity.ok(result);
    }

    @PostMapping("/dgddi/prepare-submission")
    @RolesAllowed({CompanyRole.Role.OWNER, CompanyRole.Role.ADMIN, CompanyRole.Role.MANAGER})
    public ResponseEntity<Map<String, String>> prepareSubmission(
            @RequestBody Map<String, Object> request) {
        String eori = (String) request.get("eoriNumber");
        return ResponseEntity.ok(Map.of("status", "prepared", "eori", eori != null ? eori : ""));
    }

    @GetMapping("/check-tai/{hsCode}")
    @RolesAllowed({CompanyRole.Role.OWNER, CompanyRole.Role.ADMIN, CompanyRole.Role.MANAGER, CompanyRole.Role.USER})
    public ResponseEntity<Map<String, Object>> checkTAI(@PathVariable String hsCode) {
        return ResponseEntity.ok(Map.of(
                "hsCode", hsCode,
                "hasTAI", frenchFiscalService.hasTAI(hsCode),
                "hasAccises", frenchFiscalService.hasAccises(hsCode),
                "hasSafeguard", frenchFiscalService.hasSafeguardDuty(hsCode)
        ));
    }
}
